name: Continuous Integration

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using node.js
        uses: actions/setup-node@v2
        with:
          node-version: '11.x'
      - name: run install latest
        run: npm install -g npm@latest
      - name: run install
        run: npm install
